const fs = require('fs');
const path = require('path');

const bundlePath = path.join(__dirname, '..', 'dist', 'polyfills.bundle.js');
const headerPath = path.join(__dirname, '..', 'dist', 'Polyfills.h');
const cppTargetPath = path.join(
  __dirname,
  '..',
  '..',
  '..',
  'cpp',
  'Polyfills.h'
);

const bundleContent = fs.readFileSync(bundlePath, 'utf-8');

// Use a delimiter that won't appear in the minified JS bundle
// R"POLYFILL(...)POLYFILL" allows the content to contain )" sequences
const header = `// Auto-generated file - DO NOT EDIT
// Generated by: packages/polyfills/scripts/generate-header.js

#pragma once

namespace webworker {

constexpr const char* kPolyfillScript = R"POLYFILL(
${bundleContent}
)POLYFILL";

} // namespace webworker
`;

// Ensure dist directory exists
const distDir = path.dirname(headerPath);
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

// Write to dist/
fs.writeFileSync(headerPath, header);
console.log('Header created: dist/Polyfills.h');

// Copy to cpp/
fs.copyFileSync(headerPath, cppTargetPath);
console.log('Header copied to: cpp/Polyfills.h');
